### ISSUE TITLE
webdialog not always shows tests correctly on mac

### ISSUE THREAD

**Issue by GWydouw** [SketchUp/testup-2#93] opened 2016-07-25 05:02 UTC
In about 25% of the time the web dialog don't show my tests. I need to close and reopen the web dialog two to three times before my tests show up. Sometime first only my test class shows in the tab both with no tests, sometimes also the test class don't show up.

**Comment by thomthom** [comment] 2016-07-25 16:10
Do you see any error messages in the console that might give a clue?

**Comment by GWydouw** [comment] 2016-07-25 16:12
Thomas,

No errors in the console.

Kind regards,

Guy

architectuurburo wydouw bvba
architect Guy Wydouw
 
Hoevensebaan 238 | 2950 Kapellen
T 03/327.95.67 | F 03/327.95.68 | GSM 0496/26.25.87
E-mail guy@wydouw.be | www.wydouw.be

 <http://www.wydouw.be/> <https://www.facebook.com/architectuurburo.wydouw> <https://www.facebook.com/architectuurburo.wydouw> <http://www.pinterest.com/wydouw/> <http://www.linkedin.com/pub/guy-wydouw/1b/410/51>
 <http://www.linkedin.com/pub/guy-wydouw/1b/410/51>

**Comment by syroezhkin** [comment] 2017-11-19 22:18
I get the same issue. My tests are appearing after closing and reopening a web dialog to about 3-7 times. The tests themselves work correctly. The issue is on both SketchUp Pro 2016 and 2017. I tried to install the plugin as from the lastest 2.2.0.rbz reliase, so from the master branch. Also I installed 2.1.0 and 2.0.0 versions — nothing changed.

**Comment by thomthom** [comment] 2017-11-20 09:49
Is this Window or Mac?

I wonder if sometimes the window doesn't draw properly. When you observe this, can you try to resize the dialog - does that make the content show up?

If not, can you do a quick screen video capture?

**Comment by syroezhkin** [comment] 2017-11-20 10:32
Yes, it's on the Mac. Here is the video: https://youtu.be/kXSnQa5xiA4

**Comment by Achill113** [comment] 2018-01-24 21:08
This is the same problem that I have on Windows 10 with SketchUp Pro 2017 except even resizing the window and opening and closing 20 times does not fix the issue

**Comment by macfreek** [comment] 2018-03-09 12:59
(This is a copy of report at https://bitbucket.org/thomthom/solid-inspector/pull-requests/1/examine-nested-instances/diff upon request of the author of TestUp.)

I have the same (or a very similar) issue: the tests are detected correctly in both the `TestUp.discover_tests` and `TestUp::TestUpWindow.discover_tests` methods. At least, the `discoveries` variable contained all tests.

I'm running SketchUp Pro 2018 on MacOS 10.13.3 (Ruby 2.2.4 in SketchUp).

However, the window is usually (I would say 3 out of 4 times) not updated correctly. Here are a few results, the first when closing and opening the TestUp window.

Most trivial, just a blank window:

![TestUp-empty_window.png](https://bitbucket.org/repo/Gpxap/images/3430144612-TestUp-empty_window.png)

Or the buttons are shown, but the test suite is not shown (despite that it is listed in the `discoveries` variable):

![TestUp-buttons_no_test_directory.png](https://bitbucket.org/repo/Gpxap/images/422984616-TestUp-buttons_no_test_directory.png)

Or the directory is shown, but the two test files (modules) which are detected are not displayed:

![TestUp-buttons_no_tests.png](https://bitbucket.org/repo/Gpxap/images/246642327-TestUp-buttons_no_tests.png)

Also, when the modules are loaded correctly, and I edit the code (in this example, I disabled all but 1 test in `TC_ErrorFinder.rb`), I expected that after pressing the 'rediscover' key in the TestUp window, the tests would reload. They probably do, but are not clearly updated in the TestUp user interface:

![TestUp-reload_6_or_43_tests.png](https://bitbucket.org/repo/Gpxap/images/787964869-TestUp-reload_6_or_43_tests.png)

As you see, the status line at the bottom of the window shows that it discovered 6 tests in 2 modules, but the main window is not updates (it still says 43 tests in total).

Given that in all cases, the variable `discoveries` finds all tests, the I suspect the bug is in how the window is updated, not in the discovery code.

**Comment by macfreek** [comment] 2018-03-09 13:10
This bug is tagged with "need more info". Thomas, could you let me know what info you need? I'm happy to add some debugging info (a `puts` here or there) so you can better debug it.

**Comment by thomthom** [comment] 2018-03-12 13:16
I haven't gotten around to test it on my own mac yet. I might have all the info I need. I'll see when I get to it. Right now I'm working on a revamp of the while UI, in hopes of making it faster and easier to maintain. That might "fix" a lot of the UI related issues.

Thank you very much for all the feedback.

**Comment by thomthom** [comment] 2018-09-24 04:37
Completely rewritten UI for 2.3. Closing this issue as obsolete. Reopen if you still observer this in 2.3.

**Closed by thomthom** 2018-09-24 04:37 UTC
Labels: bug, need more info
